### ISSUE TITLE
Inference on custom example

### ISSUE THREAD

**Issue by danielcrane** [ZJULearning/resa#1]
Hi there,

Thanks for sharing your code!

I was wondering if you know of any easy way to run inference on a custom sample image (that the user provides)? Or if there's any plan on adding this functionality in the near future, ideally with some kind of way to visualise the output?

Daniel

**Comment by Turoad** [comment]
Hi Daniel,

Maybe the following example code is an easy way to run inference:
```
import torch
from models.resa import RESANet
from utils.config import Config
from datasets import build_dataloader

cfg = Config.fromfile('configs/culane.py')

resa = RESANet(cfg)
resa = resa.cuda()

# random init input tensor
x = torch.randn(1, 3, 288, 800).cuda()
out = resa(x)
```

You can also get input tensor from dataloader
```
loader = build_dataloader(cfg.dataset.val, cfg, is_train=False)

img_idx = 0
x = loader.dataset[img_idx]['img'].unsqueeze(0).cuda()
out = resa(x)
```

**Comment by danielcrane** [comment]
Thanks so much!

**Comment by Turoad** [comment]
Please ref this issue:https://github.com/ZJULearning/resa/issues/2.
You can get the visualization now.
