### ISSUE TITLE
如何使用culane的验证集验证模型

### ISSUE THREAD

**Issue by fffyyy415** [ZJULearning/resa#11]
代码中call_culane_eval方法读取的是test_spit文件夹里的数据集，模型验证时summarize结果f1始终为0。将代码改为list0 = os.path.join(data_dir,'list/val.txt')，这样读取验证集数据f1也只有0.3几。

**Comment by Turoad** [comment]
Can you show me more details, how do you run?

**Comment by fffyyy415** [comment]
![image](https://user-images.githubusercontent.com/68848476/118438932-b1336b80-b717-11eb-8656-1603cd4e4608.png)
![image](https://user-images.githubusercontent.com/68848476/118438956-b7c1e300-b717-11eb-9f3d-f1187272a602.png)
![image](https://user-images.githubusercontent.com/68848476/118438989-c60fff00-b717-11eb-9311-19ddc996a277.png)
![image](https://user-images.githubusercontent.com/68848476/118439014-ce683a00-b717-11eb-969a-6cd5e750f448.png)

**Comment by Turoad** [comment]
You should modify the config file (https://github.com/ZJULearning/resa/blob/main/configs/culane.py#L74) from 'test.txt' to 'val.txt'.
You will get the result:
```
im_dir: ./data/CULane/
list_im_file: ./data/CULane/list/val.txt
width_lane: 30
iou_threshold: 0.5
im_width: 1640
im_height: 590
-----------------------------------
Evaluating the results...
tp: 24307 fp: 5891 fn: 8375
finished process file
precision: 0.804921
recall: 0.743743
Fmeasure: 0.773123
----------------------------------

```

**Comment by fffyyy415** [comment]
已解决  感谢

**Comment by nostayup** [comment]
为什么是val.txt 而不是 val_gt.txt ？这样的话验证的话不是没有标签吗？
