### ISSUE TITLE
Code license missing

### ISSUE THREAD

**Issue by paoloirrera** [ZJULearning/resa#12]
Hi thanks for the amazing work! According to [Github doc page](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository) the default copyright laws currently apply to the repository.

Is that your intent? If not could you add to the repository the license that best applies to your work?

**Comment by Turoad** [comment]
Thanks for your suggestion. I have added the LICENSE(https://github.com/ZJULearning/resa/blob/main/LICENSE).

**Comment by paoloirrera** [comment]
Thanks!
