### ISSUE TITLE
no train_val_gt.txt generated

### ISSUE THREAD

**Issue by william3863-prog** [ZJULearning/resa#13]
[
![image](https://user-images.githubusercontent.com/83808151/119125889-eb2ca680-ba64-11eb-9af6-72e42e066797.png)
](url)

**Comment by william3863-prog** [comment]
may i know why is this happening?

**Comment by Turoad** [comment]
Do you solve this problem?
I think you should generate the list first by `python tools/generate_seg_tusimple.py --root $TUSIMPLEROOT`

**Comment by william3863-prog** [comment]
yes i solved it,thanks for replying
