### ISSUE TITLE
请问输出怎么转换成图片显示

### ISSUE THREAD

**Issue by wycrystal** [ZJULearning/resa#2]
https://github.com/ZJULearning/resa/issues/1
issues1您的回答中out = resa(x), 请问out中的数据分别代表了什么，如果想查看检测得到的车道线叠加在原图上的效果，该怎么做？谢谢！

loader = build_dataloader(cfg.dataset.val, cfg, is_train=False)

img_idx = 0
x = loader.dataset[img_idx]['img'].unsqueeze(0).cuda()
out = resa(x)

**Comment by Turoad** [comment]
I will add some code for visualization.

**Comment by Turoad** [comment]
I have updated the  code.
You can get visualization just by adding `--view`.
For example:
`
python main.py configs/culane.py --gpus 0 3 --validate --load_from culane_resnet50.pth --view
`
You will get the result in directory: `work_dirs/CULane/xxx/vis`.

As for the example:
```
import torch
import cv2
import torch.nn.functional as F
from models.resa import RESANet
from utils.config import Config
from datasets import build_dataloader
from models.registry import build_net

cfg = Config.fromfile('configs/culane.py')

resa = build_net(cfg)
resa = torch.nn.parallel.DataParallel(
                resa, device_ids = range(1)).cuda()

loader = build_dataloader(cfg.dataset.val, cfg, is_train=False)

pretrained_model = torch.load('resa50_75_3.pth')
resa.load_state_dict(pretrained_model['net'], strict=True)

img_idx = 0
x = loader.dataset[img_idx]['img'].unsqueeze(0).cuda()
with torch.no_grad():
    out = resa(x)
    probmap, exist = out['seg'], out['exist']
    probmap = F.softmax(probmap, dim=1).squeeze().cpu().numpy()
    exist = exist.squeeze().cpu().numpy()

coords = loader.dataset.probmap2lane(probmap, exist)

img_path = loader.dataset[img_idx]['meta']['full_img_path']
img = cv2.imread(img_path)
loader.dataset.view(img, coords, './test.png')

```
You will get the `test.png` in the directory `resa`.
