### ISSUE TITLE
Inference Code

### ISSUE THREAD

**Issue by KnightHarute** [ZJULearning/resa#20]
Would you consider add the inference code in the future, just like you did in another project https://github.com/Turoad/lanedet  ?
I tried the detect.py in that project, it works.
But when I try detect.py in this project, it failed, and I have no idea how to modify the code in order to fit in this project.
And sorry for reopening an issue with the same kind of problem.

**Comment by Turoad** [comment]
Currently, I'm busy for other projects and I have no plan for adding the inference code.
If you are interested in making a PR, I would be happy to provide some guidance.
