### ISSUE TITLE
DLL load failed error

### ISSUE THREAD

**Issue by GunGoo** [ZJULearning/resa#24]
![2021-06-30 18_47_13-Windows PowerShell](https://user-images.githubusercontent.com/31325556/124040825-aab13880-d9d3-11eb-9028-83006da7a1ca.png)

I got this error while following the install guide. Any suggestions? thanks in advance

**Comment by Turoad** [comment]
Have you built the project following the README.md (https://github.com/Turoad/lanedet/blob/main/README.md).
By the way, please raise issue in https://github.com/Turoad/lanedet/issues, if ithe issue is related to that project.
