### ISSUE TITLE
about stride of resa

### ISSUE THREAD

**Issue by Cverlpeng** [ZJULearning/resa#26]
您好，
我阅读了代码，发现四次迭代的stride分别为2, 4, 8, 16， 并未实现论文中列举的1,2,4,8....，比较好奇为什么不去实现stride=1呢？
另外，我理解是以stride=2为例，x0位置 = x0+x2的特征信息，x1位置 = x1 + x3 ....，其实本质是特征图的错位相加。由于是对整个特征图(c,h,w)做的conv，似乎没有真正意义上的: x2n->.....->x8->x6->x4->x2->x0这样类似与SCNN的信息传递，似乎没有一个特征信息从下到上一直传递（类似预resnet跳跃链接），这是不是一个方向需要多次迭代的原因呢？或者可以解释一下为什么一个方向需要多次迭代吗？
非常期待您的解答，谢谢！

**Comment by Turoad** [comment]
Thanks for your interest.
- *About Stride.*  In the paper, it's a more general way to define the stride. In our setting, stride = 2,4,8,16.  We can also use stride = 1,2,4,8,16, but inference may be slower.  The experiment result is also similar.  The reason why we use different strides is to help network gather global information like ASPP. The `stride` is similar to `dilation`. The information may be similiar between adjacent featuremap slice (i.e, stride = 1), thus it may not help network gather more information.
- *About message passing.* Addition is one message passing method.  The skip connection in ResNet also uses the addition. 
- *About iteration.* In our paper, we have analyzed the iteration and how it gather the information. Please see the Figure 3 in our paper and the related analysis.

**Comment by Cverlpeng** [comment]
感谢你的解答！
