### ISSUE TITLE
about tusimple val_dataset and test_dataset

### ISSUE THREAD

**Issue by lsbsir** [ZJULearning/resa#28]
作者你好，
我看了您的tusimple数据集的配置文件，对验证集和测试集为什么都选用tusimple数据集的test_gt.txt产生了疑问。按照通常来做，不应该验证集选val_gt.txt，测试集选test_gt.txt，如果验证集和测试集都选择同一个，那个保存的模型对测试集就不是‘未知’的了，那么是否会因为过拟合而造成结果不准确呢？期望你的解答

**Comment by Turoad** [comment]
We train the model in training + validate set, and test it on test set.
