### ISSUE TITLE
about exist branch loss

### ISSUE THREAD

**Issue by Cverlpeng** [ZJULearning/resa#29]
你好！
在ExistHead()类中最后对输入进行了torch.sigmod()激活，为什么在计算loss时还选择BCEWithLogitsLoss()而不是BCELoss(), BCEWithLogitsLoss()不是sigmod() + BCEloss()，这会影响网络训练吗？

谢谢！

**Comment by Starboy-at-earth** [comment]
你是咋解决的 确实不合理

**Comment by Turoad** [comment]
Yes, you're right. It should be `BCEloss`. We have updated this loss, the final F1 is similar with `BCEWithLogitsLoss`.
