### ISSUE TITLE
CPU mode

### ISSUE THREAD

**Issue by phylliskaka** [ZJULearning/resa#3]
Hi There, 

Thanks for sharing the source code. I am trying to run the model on a server without GPU. Does this model support CPU mode? Thanks in advance.

**Comment by Turoad** [comment]
Yes. I have tested it. This model can run in cpu device.

**Comment by phylliskaka** [comment]
Can you show your command to run with the cpu device ? Thanks.

**Comment by Turoad** [comment]
I just remove `.cuda()` in the following code:
```
import torch
from models.resa import RESANet
from utils.config import Config
from datasets import build_dataloader

cfg = Config.fromfile('configs/culane.py')

resa = RESANet(cfg)
resa = resa.cuda()

# random init input tensor
x = torch.randn(1, 3, 288, 800).cuda()
out = resa(x)
```
