### ISSUE TITLE
hyperparameters about the RESA module

### ISSUE THREAD

**Issue by qklee-lz** [ZJULearning/resa#31]
您好：
您提出resa对车道线检测非常具有创新性，我想把此模块插入到我的网络模型中，我的网络backbone是基于resnet18修改的，特征图输出是(Batch, 128, 12, 20) 请问如果使用这种12x20的小特征图，会不会对resa的聚合效果有所影响，如果影响较大您建议的最小hw维度应该为多少呢？如果12x20的小特征图也能接受，是不是需要调整resa中的"conv_stride=9"的超参数，"alpha=2.0"的超参数是不是一般不需要改动。
十分需要您的解答，非常感谢！🙏💗

**Comment by nostayup** [comment]
请问你做实验了吗？最后的效果怎么样？

**Comment by Turoad** [comment]
小的特征图应该是可以接受的。具体参数调整我建议你根据具体的实验情况而定。

**Comment by 2696120622** [comment]
@qklee-lz @Turoad alpha 的值影响大吗？设置成多少合适？
