### ISSUE TITLE
How can I get the runtime and FPS values of the model

### ISSUE THREAD

**Issue by 869636929** [ZJULearning/resa#32]
How can I get the runtime and FPS values of the model.Thank You

**Comment by Turoad** [comment]
You can try code like this:
```
import torch
import cv2
import torch.nn.functional as F
from models.resa import RESANet
from utils.config import Config
from datasets import build_dataloader
from models.registry import build_net
import time

cfg = Config.fromfile('configs/culane.py')

resa = build_net(cfg)
resa = resa.cuda()
resa.eval()

loader = build_dataloader(cfg.dataset.val, cfg, is_train=False)


img_idx = 0
#x = loader.dataset[img_idx]['img'].unsqueeze(0).cuda()
x = torch.randn(1, 3, 288, 800).cuda()

w_iter = 200
iter = 1000

# warm up
for i in range(w_iter):
    out = resa(x)

total_time = 0.
for i in range(iter):
    start = time.time()
    resa(x)
    end = time.time()
    total_time += (end - start)
print(total_time/iter)


```

**Comment by 869636929** [comment]
Ok, thank you very much



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月4日(星期五) 下午3:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ZJULearning/resa] How can I get the runtime and FPS values of the model (#32)





 
You can try code like this:
 import torch import cv2 import torch.nn.functional as F from models.resa import RESANet from utils.config import Config from datasets import build_dataloader from models.registry import build_net import time cfg = Config.fromfile('configs/culane.py') resa = build_net(cfg) resa = resa.cuda() resa.eval() loader = build_dataloader(cfg.dataset.val, cfg, is_train=False) img_idx = 0 #x = loader.dataset[img_idx]['img'].unsqueeze(0).cuda() x = torch.randn(1, 3, 288, 800).cuda() w_iter = 200 iter = 1000 # warm up for i in range(w_iter):     out = resa(x) total_time = 0. for i in range(iter):     start = time.time()     resa(x)     end = time.time()     total_time += (end - start) print(total_time/iter)  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
