### ISSUE TITLE
line index generated

### ISSUE THREAD

**Issue by xiezhang666** [ZJULearning/resa#33]
The line index generated by this formula
   idx_d = (torch.arange(self.height) + self.height //
                     2**(self.iter - i)) % self.height
  1. my question is where the idea come from ?
  2. Can it use  [1, 2, 4, 8 ,16] as index ? it leads to bad performance?

thanks~

**Comment by Turoad** [comment]
1. The stride can be considered as dilation in Conv. The idea is similar in ASPP for segmentation.  I show the figs below:
ASPP
![image](https://user-images.githubusercontent.com/36562593/156712163-e654032c-5175-4a3e-ac26-02e10453200a.png)
RESA
![image](https://user-images.githubusercontent.com/36562593/156712261-3967aa07-c814-440e-bb19-e85fa4b4fb34.png)
3. You can have a try. The performace is similar.

**Comment by Turoad** [comment]
We will close this issue first. Feel free to reopen it if you have any questions.
