### ISSUE TITLE
关于上采样的一些疑惑

### ISSUE THREAD

**Issue by nostayup** [ZJULearning/resa#35]
在分割中，编码的输出和对应分辨率的解码输出进行级联是很常见的，
为什么咱们的解码模块只是单纯的进行上采样？没有和编码的级联呢？

**Comment by Turoad** [comment]
可以采用分割的方法，我们在paper里面也设计了一种decoder。直接单纯的上采样在车道线检测里面效果也不错，并且速度非常快，所以为了保证一定的推理速度，我们采用直接上采样。
