### ISSUE TITLE
About the resnet34 training culane dataset

### ISSUE THREAD

**Issue by AKakuku** [ZJULearning/resa#36]
Hello author!  Congratulations on your outstanding results. Your ideas have also inspired me a lot. Here I used resnet_34 as backbone to train the culane dataset. The change in configs/culane.py is to change both img_height and img_width to 512, and iter from 4  It has become 5, and the F1 score of the model trained on this basis is only about 71. Can you give me some suggestions?I would appreciate it!🙂

**Comment by nostayup** [comment]
iter算出来不应该是6吗？

**Comment by Turoad** [comment]
I haven't tried the setting `img_height =img_width= 512`, it may influence the result.
