### ISSUE TITLE
Unable to find the feature aggregation with different strides aspect as mentioned in the paper

### ISSUE THREAD

**Issue by sakethbachu** [ZJULearning/resa#38]
Hello

I am unable to understand in the code how feature aggregation with different stride as mentioned in the paper (also in the picture present in the readme of this repo) is implemented. Any insight will be very helpful.

Thanks in advance!

**Comment by Turoad** [comment]
The implementation is in: https://github.com/ZJULearning/resa/blob/main/models/resa.py#L61-L71.
You may focus on this code, it first gets the shifted feature with `conv(x[..., idx, :]` then adds to the original feature.
```
x.add_(self.alpha * F.relu(conv(x[..., idx, :])))
```
Please let me know if you have further questions.

**Comment by Turoad** [comment]
We will close this issue first. Feel free to reopen it if you have any questions.

**Comment by 2696120622** [comment]
> The implementation is in: https://github.com/ZJULearning/resa/blob/main/models/resa.py#L61-L71. You may focus on this code, it first gets the shifted feature with `conv(x[..., idx, :]` then adds to the original feature.
> 
> ```
> x.add_(self.alpha * F.relu(conv(x[..., idx, :])))
> ```
> 
> Please let me know if you have further questions.

@Turoad What this self.alpha does? Is there some suggestions for setting its value?
