### ISSUE TITLE
no such file 

### ISSUE THREAD

**Issue by miao02830** [ZJULearning/resa#41]
![image](https://user-images.githubusercontent.com/27732256/159833957-742c13f2-cc21-41b0-94a7-da5722ca9b06.png)

Hello,author~ I encountered this problem during running training. I don't know how to solve it. Please help me

**Comment by Turoad** [comment]
Build the evaluator as the README suggests.
```
cd $RESA_ROOT/runner/evaluator/culane/lane_evaluation
make
cd -
```

**Comment by miao02830** [comment]
okay  ths!
