### ISSUE TITLE
image flipping

### ISSUE THREAD

**Issue by lcwcwl** [ZJULearning/resa#45]
Hello, I have a question to ask. I saw that image flipping was used for data enhancement, but the instance label did not change. For example, the left label is 1, 2, 3, and the right label is 4, 5, 6, According to the label definition, when the slope is negative, the label is 1, 2, 3. After flipping, the labels 4, 5, and 6 don't need to become 1, 2, and 3? I don't know if there is a problem with my understanding. I look forward to receiving your reply, thank you!

**Comment by Turoad** [comment]
Nice question. I think you might be right. The exist label should also be flipped.
Could you try it and see whether the performance will be improved ?

**Comment by lcwcwl** [comment]
Thank you for your reply, I tried to remove the flipping directly, which has little effect on the results. I will try it you said and see whether the performance is improving.The probability of flipping in the code is 0.5, why does it not have a great impact on the result ? I don’t know how to understand this. Can I give your opinion? Thanks!

**Comment by Turoad** [comment]
We don't have instance label, only exist label, 1 stand for lane is exised, 0 is not. For example, [1,1,1,0] means the image has two left lanes, one right lane. We don't number it as 1,2,3,4,5, ... 

If filp, [1,1,1,0] should be [0,1,1,1], are you using this method?

**Comment by lcwcwl** [comment]
Thanks! The acc in my custom data improves 2% after changing the exist label when I used image flipping.

**Comment by Turoad** [comment]
Do you try the CULane or Tusimple?
