### ISSUE TITLE
Where is this file? python scripts/generate_seg_tusimple.py --root $TUSIMPLEROOT

### ISSUE THREAD

**Issue by aizzat** [ZJULearning/resa#5]
python scripts/generate_seg_tusimple.py --root $TUSIMPLEROOT

**Comment by Turoad** [comment]
It's fixed by this commit: https://github.com/ZJULearning/resa/commit/fef87dde3f5a64c7b3aefa777a04236fc0d89d70
The command is:
```
python tools/generate_seg_tusimple.py --root $TUSIMPLEROOT
```

**Comment by aizzat** [comment]
Thanks!

**Comment by GeneralJing** [comment]
使用这个命令报错了：
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 1353 (char 1352)
是下载的文件有问题吗？
我得到的$TUSIMPLEROOT/lable_data_xxxx.json # label json file x4文件这个地方只有三个，
label_data_0313.json label_data_0531.json label_data_0601.json

**Comment by ilaij0810** [comment]
@GeneralJing   this error is for the reason that the 'test_label.json' file was not fully downloaded。

**Comment by GeneralJing** [comment]
thank you. i will try that later.
