### ISSUE TITLE
CULane数据集评估

### ISSUE THREAD

**Issue by wq1148927746** [ZJULearning/resa#6]
您好！
        感谢您的贡献。我在B站也看到过您分享的视频。但是在我动手学习您的代码时存在下面问题：

        在_resa/configs/culane.py /_文件中，关于数据集的描述如下：

_dataset = dict(
    train=dict(
        type='CULane',
        img_path=dataset_path,
        data_list='train_gt.txt',
    ),
    val=dict(
        type='CULane',
        img_path=dataset_path,
        data_list='test_img.txt',
    ),
    test=dict(
        type='CULane',
        img_path=dataset_path,
        data_list='test_img.txt',
    )
)_

可是在我下载的CULane数据集中不存在_test_img.txt_文件，并且我下载的数据集中没有对测试集ground truth的标注信息。不知道是我下载的数据集有问题吗？
由此导致我无法评估准确率等指标，令我十分困扰。

十分感谢您的回答！

**Comment by wq1148927746** [comment]
![QQ图片20210503212249](https://user-images.githubusercontent.com/47206549/116881538-f5be0200-ac55-11eb-993d-4a0dafd00131.png)


这是我下载的CULane数据集中list文件夹的情况。

**Comment by Turoad** [comment]
感谢关注。B站上分享的是另一个作者哈。
你下载的数据集没啥问题的哈。
这个问题是为了统一训练集和测试集格式带来的。
`test_img.txt`加入了测试集的标签，但我们没有用，这个我们加入的时候疏忽了，原数据集没有的。
后续我会提交一个commit修复这个问题。

**Comment by Turoad** [comment]
感谢关注。B站上分享的是另一个作者哈。
你下载的数据集没啥问题的哈。
这个问题是为了统一训练集和测试集格式带来的。
`test_img.txt`加入了测试集的标签，但我们没有用，这个我们加入的时候疏忽了，原数据集没有的。
后续我会提交一个commit修复这个问题。

**Comment by wq1148927746** [comment]
> 感谢关注。B站上分享的是另一个作者哈。
> 你下载的数据集没啥问题的哈。
> 这个问题是为了统一训练集和测试集格式带来的。
> `test_img.txt`加入了测试集的标签，但我们没有用，这个我们加入的时候疏忽了，原数据集没有的。
> 后续我会提交一个commit修复这个问题。

感谢您百忙之中的回复。再次感谢您的contribution.

**Comment by Turoad** [comment]
https://github.com/ZJULearning/resa/commit/55f7405011cd6764a73a939d02c54d989ec55d3d 这个提交已经修复了。可以再测试下。

**Comment by wq1148927746** [comment]
> [55f7405](https://github.com/ZJULearning/resa/commit/55f7405011cd6764a73a939d02c54d989ec55d3d) 这个提交已经修复了。可以再测试下。

再次感谢！
