### ISSUE TITLE
关于数据归一化问题

### ISSUE THREAD

**Issue by Lu-Chengyu** [ZJULearning/resa#7]
很棒的工作，让人受益匪浅。
但是我在看您代码的过程中发现，对于数据的预处理您做的是标准化而不是归一化，这样是否会比较容易产生梯度爆炸的现象呢，因为我尝试将您的网络和其他网络相接训练，总是会出现训练没多久就变成nan的情况。
另外我看到标准化过程中您用的似乎是imagenet的均值和1的标准差，对于在tusimple和culane上的训练是否会产生影响呢
谢谢

**Comment by Lu-Chengyu** [comment]
另外我还有一个疑惑就是img_height = 368，img_width = 640，cut_height = 160是如何确定的，谢谢

**Comment by Turoad** [comment]
We have tried to normalize the input image to [0, 1] in our experiment before, it produces the similiar result. It will not have influence on the gradient exploding problem.

As for the input size, we follow the paper https://arxiv.org/pdf/1908.00821.pdf. In tusimple dataset,  there is no lane in the upper areas of the input image, thus cut_height is counted from the dataset.

**Comment by Lu-Chengyu** [comment]
谢谢，应该是我相接的网络对输入的归一化比较敏感，在我把输入归一化后不会在出现nan的问题了
